openapi: 3.0.0
info:
  title: E-commerce Toys API
  description: "API de E-commerce de Juguetes para el Bootcamp TOP Full Stack de Make it Real. Tecnologías utilizadas: Node.js, TypeScript, Express, PostgreSQL, Prisma, JWT, Swagger. Desarrollado por: Valeria Lozano."
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Servidor de desarrollo

tags:
  - name: Auth
    description: Operaciones relacionadas con la autenticación de usuarios
  - name: Users
    description: Operaciones relacionadas con los usuarios
  - name: Admins
    description: Operaciones relacionadas con los administradores
  - name: Categories
    description: Operaciones relacionadas con las categorías
  - name: Brands
    description: Operaciones relacionadas con las marcas
  - name: Materials
    description: Operaciones relacionadas con los materiales
  - name: Discounts
    description: Operaciones relacionadas con los descuentos
  - name: Products
    description: Operaciones relacionadas con los productos
  - name: Images
    description: Operaciones relacionadas con las imágenes de los productos
  - name: Carts
    description: Operaciones relacionadas con los carritos de compra

paths:
  # AUTH
  /users/login:
    post:
      tags:
        - Auth
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/userLogin"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/responses/userLogin"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"

  /admins/login:
    post:
      tags:
        - Auth
      summary: Iniciar sesión como administrador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/adminLogin"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/responses/adminLogin"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"

  # USERS
  /users:
    get:
      tags:
        - Users
      summary: Obtener todos los usuarios
      security:
        - bearerAuth: []
      responses:
        200:
          $ref: "#/components/responses/user"
        500:
          $ref: "#/components/responses/InternalServerError"

    post:
      tags:
        - Users
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/userCreate"
      responses:
        201:
          description: Creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/{id}:
    get:
      tags:
        - Users
      summary: Obtener un usuario por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      responses:
        200:
          $ref: "#/components/responses/user"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

    put:
      tags:
        - Users
      summary: Actualizar un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/userUpdate"
      responses:
        200:
          $ref: "#/components/responses/user"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

    delete:
      tags:
        - Users
      summary: Eliminar un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      responses:
        200:
          $ref: "#/components/responses/user"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/email/{email}:
    get:
      tags:
        - Users
      summary: Obtener un usuario por correo electrónico
      security:
        - bearerAuth: []
      parameters:
        - name: email
          in: path
          required: true
          description: Correo electrónico del usuario
          schema:
            $ref: "#/components/bases/email"
      responses:
        200:
          $ref: "#/components/responses/user"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/password/{id}:
    patch:
      tags:
        - Users
      summary: Actualizar la contraseña de un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updatePassword"
      responses:
        200:
          $ref: "#/components/responses/user"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/{id}/image:
    patch:
      tags:
        - Users
      summary: Actualizar la imagen de perfil de un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  $ref: "#/components/bases/image"
      responses:
        200:
          $ref: "#/components/responses/user"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/{id}/delete-image:
    patch:
      tags:
        - Users
      summary: Eliminar la imagen de perfil de un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      responses:
        200:
          $ref: "#/components/responses/user"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/{id}/activate:
    patch:
      tags:
        - Users
      summary: Activar un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      responses:
        200:
          $ref: "#/components/responses/user"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

  /users/{id}/deactivate:
    patch:
      tags:
        - Users
      summary: Desactivar un usuario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            $ref: "#/components/bases/id"
      responses:
        200:
          $ref: "#/components/responses/user"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Token JWT para autenticación. Los usuarios autenticados pueden tener uno de los siguientes roles: "admin", "user".'

  # RESPONSES
  responses:
    # GENERAL
    BadRequest:
      description: Datos no válidos. La solicitud no se puede procesar debido a errores de cliente.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Datos no válidos. Asegúrate de que todos los campos requeridos estén presentes y sean correctos."
              validationErrors:
                type: array
                items:
                  type: string
                example:
                  [
                    "El campo 'nombre' es requerido.",
                    "La dirección de correo electrónico no es válida.",
                    "Ya existe un usuario con el correo electrónico",
                  ]

    Unauthorized:
      description: No autenticado. Se requiere un token válido.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "No autenticado. Se requiere un token válido."

    Forbidden:
      description: No tienes permisos para acceder a este recurso.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Acceso prohibido. No tienes los permisos necesarios."

    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "No se encontró el recurso solicitado"

    InternalServerError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error interno del servidor"

    # AUTH
    userLogin:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/user"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIwZjQwZjIwZjIwZjIwZjIwZjIwZjIiLCJyb2xlIjoidXNlciIsImlhdCI6MTYzMDIwNjQwMCwiZXhwIjoxNjMwMjA2NDAwfQ.7"

    adminLogin:
      type: object
      properties:
        admin:
          $ref: "#/components/schemas/admin"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIwZjQwZjIwZjIwZjIwZjIwZjIwZjIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzAyMDY0MDAsImV4cCI6MTYzMDIwNjQwMH0.7"

    # USERS
    user:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/user"

  # BASES
  bases:
    id:
      type: string
      example: "jndasl97jnias7280004872nk"
      description: Identificador único del recurso

    fullName:
      type: string
      example: "John Doe"
      description: Nombre completo del usuario

    email:
      type: string
      example: "john.doe@example.com"
      description: Correo electrónico del usuario, debe cumplir con el formato de un correo electrónico válido

    username:
      type: string
      example: "johndoe"
      description: Nombre de usuario del administrador

    password:
      type: string
      example: "Abcd1234_"
      description: Contraseña del usuario, debe tener al menos 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial

    passwordHash:
      type: string
      example: "$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36FjsdY4Z5k6Q5J5Z5J5J5K"
      description: Contraseña del usuario encriptada

    image:
      type: string
      format: binary
      description: Imagen a subir.

  # REQUEST BODIES
  requestBodies:
    # AUTH
    userLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          $ref: "#/components/bases/email"
        password:
          $ref: "#/components/bases/password"

    adminLogin:
      type: object
      required:
        - username
        - password
      properties:
        username:
          $ref: "#/components/bases/username"
        password:
          $ref: "#/components/bases/password"

    # UPDATE_PASSWORD
    updatePassword:
      type: object
      required:
        - password
      properties:
        password:
          $ref: "#/components/bases/password"

    # USERS
    userCreate:
      type: object
      required:
        - fullName
        - email
        - password
      properties:
        fullName:
          $ref: "#/components/bases/fullName"
        email:
          $ref: "#/components/bases/email"
        password:
          $ref: "#/components/bases/password"

    userUpdate:
      type: object
      properties:
        fullName:
          $ref: "#/components/bases/fullName"
        email:
          $ref: "#/components/bases/email"

  # SCHEMAS
  schemas:
    # USERS
    user:
      type: object
      required:
        - fullName
        - email
        - passwordHash
      properties:
        id:
          $ref: "#/components/bases/id"
        fullName:
          $ref: "#/components/bases/fullName"
        email:
          $ref: "#/components/bases/email"
        passwordHash:
          $ref: "#/components/bases/passwordHash"
        profileImage:
          type: string
          nullable: true
          example: "https://example.com/images/profile.jpg"
        cart:
          type: object
          properties:
            id:
              type: string
              example: "cart123"
        orders:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: "order123"
        createdAt:
          type: string
          format: date-time
          example: "2021-09-01T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-09-01T00:00:00.000Z"
        isDeleted:
          type: boolean
          example: false

    # ADMINS
    admin:
      type: object
      required:
        - fullName
        - email
        - username
        - passwordHash
      properties:
        id:
          type: string
          example: "jndasl97jnias7280004872nk"
        fullName:
          type: string
          example: "Jane Doe"
        email:
          type: string
          example: "jane.doe@example.com"
        username:
          type: string
          example: "janedoe"
        passwordHash:
          type: string
          example: "$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36FjsdY4Z5k6Q5J5Z5J5J5K"
        profileImage:
          type: string
          nullable: true
          example: "https://example.com/images/profile.jpg"
        createdAt:
          type: string
          format: date-time
          example: "2021-09-01T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-09-01T00:00:00.000Z"
        isDeleted:
          type: boolean
          example: false
